# Use a imagem oficial do Node.js como base
FROM node:16

# Defina o diretório de trabalho no contêiner
WORKDIR /app

# Copie o arquivo package.json e package-lock.json para o contêiner
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie os arquivos do seu projeto para o contêiner
COPY . .

# Exponha a porta que o Next.js usará (se necessário)
# EXPOSE 3000

# Comando para iniciar o servidor Next.js
CMD ["npm", "run", "dev"]
